{{- if or (.Values.extraConfigs) (.Values.configs) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- if .Values.configs }}
{{- include "common.tplvalues.render" ( dict "value" .Values.configs "context" $ ) | nindent 2 }}
{{- end }}
{{- with .Values.extraConfigs }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}