{{- define "external-ingress-auth.name" -}}
    {{- template "external-ingress-auth.trim" (list (.Release.Name | lower) 27) }}-{{- template "external-ingress-auth.trim" (list (.Chart.Name | lower) 36) }}
{{- end }}

{{- define "external-ingress-auth.trim" }}
{{- $value := kindIs "slice" . | ternary (index . 0) . }}
{{- $len := kindIs "slice" . | ternary (index . 1) 32 }}
{{- $value | trunc $len | trimSuffix "-" }}
{{- end }}

{{- define "external-ingress-auth.labels.selectors" -}}
app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" | quote }}
app.kubernetes.io/part-of: {{ .Release.Name }}
{{- end }}


{{- define "external-ingress-auth.labels" -}}
{{ include "external-ingress-auth.labels.selectors" (index . 0) }}
app.kubernetes.io/version:	{{ (index . 0).Chart.Version | quote }}
app.kubernetes.io/managed-by: {{ (index . 0).Release.Service | quote }}
{{- range $name, $value := merge (index . 1) (index . 0).Values.commonLabels }}
{{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}

{{- define "external-ingress-auth.annotations" -}}
{{- range $name, $value := merge (index . 1) (index . 0).Values.commonAnnotations }}
{{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}

{{- define "external-ingress-auth.rule" }}
{{- include "external-ingress-auth.rule-part" .hosts -}}:
{{- include "external-ingress-auth.rule-part" .ranges -}}:
{{- include "external-ingress-auth.rule-part" .methods -}}:
{{- include "external-ingress-auth.rule-part" .paths -}}:
{{- if .public -}}
<public>
{{- else -}}
{{- include "external-ingress-auth.rule-part" .users -}}
{{- if .groups -}}
:{{- include "external-ingress-auth.rule-part" .groups -}}
{{- with .operators -}}
:{{ default "OR" .groups }}:{{ default "AND" (get . "users-and-groups") -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}


{{- define "external-ingress-auth.rule-part" -}}
{{- if . }}{{ join "," . }}{{ else }}**{{ end }}
{{- end -}}