{{- with .Values.config.authorization }}
{{- with .rules }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "external-ingress-auth.name" $ }}-rules
  namespace: "{{ $.Release.Namespace }}"
  labels: {{- include "external-ingress-auth.labels" (list $ dict) | nindent 4 }}
  annotations: 
    {{- include "external-ingress-auth.annotations" (list $ dict) | nindent 4 }}  
data:
  rules: |
  {{- range $_, $r := . }}
    {{ include "external-ingress-auth.rule" . }}
  {{- end }}
{{- end }}

{{- if and .ingressRules.enabled (not .ingressRules.secret.external.name) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "external-ingress-auth.name" $ }}-rules-secret
  namespace: "{{ $.Release.Namespace }}"
  labels: {{- include "external-ingress-auth.labels" (list $ dict) | nindent 4 }}
  annotations: 
    {{- include "external-ingress-auth.annotations" (list $ dict) | nindent 4 }}  
stringData:
  {{ tpl .ingressRules.secret.external.key $ }}: {{ tpl .ingressRules.secret.value $ | quote }}
{{- end }}
{{- end }}
