{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "external-ldap-auth.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "external-ldap-auth.labels" (list . .Values.ingress.labels) | nindent 4 }}
  annotations: {{- include "external-ldap-auth.annotations" (list . .Values.ingress.annotations) | nindent 4 }}  
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ template "external-ldap-auth.name" . }}
                port:
                  name: http
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}