# -- common labels for all resources deployed by this chart
commonLabels: {}
# -- common annotations for all resources deployed by this chart
commonAnnotations: {}

config:
  # -- environment-variables for configuration of the service; can be templated e.g to use helm-values
  #    see https://github.com/Argelbargel/external-ldap-auth#environment-variables for allowed keys and values
  env: {}
  # -- further configuration-sources (e.g. secrets for manager-dn and password); can be templated e.g to use helm-values
  envFrom: []

image:
  # -- overrides the image-repo for the deployed container-image 
  repo: "ghcr.io/argelbargel/external-ldap-auth"
  # -- overrides the image-tag for the deployed container-image 
  # @default -- .Chart.AppVersion
  tag:
  pullPolicy: IfNotPresent
  # -- image-pull-secrets; can be templated e.g to use helm-values
  pullSecrets: []

deployment:
  replicas: 1
  # -- additional labels specific to the deployment resource
  labels: {}
  # -- additional annotations specific to the deployment resource
  annotations: {}
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi
  # -- initContainers for the deployment; can be templated e.g to use helm-values
  initContainers: []
  # -- additional volume mounts for the external-ldap-auth-container; can be templated e.g to use helm-values
  volumeMounts: []
  # -- additional volumes for the deployment; can be templated e.g to use helm-values
  volumes: []

service:
  type: ClusterIP
  # -- additional labels specific to the service resource
  labels: {}
  # -- additional annotations specific to the service resource
  annotations: {}

serviceMonitor:
  enabled: false
  # -- additional labels specific to the service-monitor resource
  labels: {}
  # -- additional annotations specific to the service-monitor resource
  annotations: {}

ingress:
  enabled: false
  # -- additional labels specific to the ingress resource
  labels: {}
  # -- additional annotations specific to the ingress resource
  annotations: {}
  host: ""
  tls:
    enabled: false
    secretName: ""
