name: Build Container Image

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  pull-requests: read
  packages: write

concurrency:
  group: build-image-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Extract metadata (tags, labels) of Image
      id: image-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Login to Github Packages
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Build image and push to GitHub Container Registry
      id: build
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./docker
        file: ./docker/Dockerfile
        tags: ${{ steps.image-meta.outputs.tags }}
        labels: ${{ steps.image-meta.outputs.labels }}
