name: Build Container Image

permissions:
  contents: read
  pull-requests: read
  packages: write

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
    - "v**.**.**"

concurrency:
  group: build-image-${{github.ref}}
  cancel-in-progress: true

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Ensure valid image ref
      id: image-ref
      run: |
        echo "ref=${IMAGE_REGISTRY}/${IMAGE_NAME,,}" >> $GITHUB_OUTPUT

    - name: Extract metadata (tags, labels) of Image
      id: image-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{steps.image-ref.outputs.ref}}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}

    - name: Login to Github Packages
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{env.IMAGE_REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: "Checkout repository"
      uses: actions/checkout@v4

    - name: Build image and push to GitHub Container Registry
      id: build
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: .
        tags: ${{steps.image-meta.outputs.tags}}
        labels: ${{steps.image-meta.outputs.labels}}
