name: Release Charts

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
  workflow_call:


concurrency:
  group: release-charts-${{ github.ref }}
  cancel-in-progress: true

env:
  CHARTS_DIR: ./charts
  HELM_DOCS_VERSION: 1.14.2

jobs:
  release-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: ${{ env.CHARTS_DIR }}
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  #        CR_RELEASE_NAME_TEMPLATE: ${{ needs.determine-release-version.outputs.current }}

  release-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        path: ./main

    - name: Checkout Pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: ./pages

    - name: Copy READMEs
      run: |
        cd ./main/$CHARTS_DIR
        find . -type f -name README.md -exec cp --parents {} $GITHUB_WORKSPACE/pages \;

    - name: Sync README.md to pages
      run: |
        cd ./pages
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit --signoff -am "Sync READMEs for ${{github.ref_name}}"
        git push
