name: Release Charts

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  pages: write

concurrency:
  group: release-charts-${{ github.ref }}
  cancel-in-progress: true

env:
  CHARTS_DIR: ./charts

jobs:
  release-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4

    #    - name: Install helm-docs
    #      run: |
    #        curl https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz \
    #            --silent --show-error --fail --location --output /tmp/helm-docs.tar.gz
    #            tar -xf /tmp/helm-docs.tar.gz helm-docs
    #    - name: Replace templates with actual README for charts
    #      run: |
    #        ./helm-docs
    #        find $CHARTS_DIR -type f -name README.md.gotmpl -exec rm {} +

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      with:
        charts_dir: ${{ env.CHARTS_DIR }}
      env:
        CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

#        CR_RELEASE_NAME_TEMPLATE: ${{ needs.determine-release-version.outputs.current }}
