name: Run unit-tests

permissions:
  contents: write
  pull-requests: read
  security-events: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - "src/**"
    - "requirements.txt"
    - "Dockerfile"
    - ".github/workflows/run-tests.yml"
  pull_request:
    branches: [ main ]
    paths:
    - "src/**"
    - "requirements.txt"
    - "Dockerfile"
    - ".github/workflows/run-tests.yml"

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        apt-get install libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev      
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest ./src --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml --cov-report=html
