name: Scan for vulnerabilities

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: '00 03 * * *'

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME,,}}:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.30.0
      with:
        image-ref: '${{env.IMAGE_REGISTRY}}/${{env.IMAGE_NAME,,}}:${{ github.sha }}'
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
