name: Update Chart-READMEs

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ main ]
    paths:
    - 'charts/**/Chart.yaml'
    - 'charts/**/values.yaml'
    - 'charts/**/README.md.gotmpl'
    - '.github/workflows/update-chart-readmes.yml'

concurrency:
  group: update-chart-readmes-${{ github.ref }}
  cancel-in-progress: true

env:
  CHARTS_DIR: ./charts
  HELM_DOCS_VERSION: 1.14.2

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run helm-docs
      run: |
        curl --silent --show-error --fail --location --output /tmp/helm-docs.tar.gz \
            https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz
        tar -C /tmp -xf /tmp/helm-docs.tar.gz helm-docs
        /tmp/helm-docs -c ${CHARTS_DIR}

    - name: Push READMEs
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add .
        git commit --signoff -am "Update chart READMEs"
        git push
